export const userURLs = {
  Login : '/login',
  SignUp : '/signup',
  ResetPassword : '/resetPassword',
  CategoriesAndSubCategories : '/products/getCategoriesAndSubCategories',
  CategoryProducts : '/products/getProducts/category/',
  SubCategoryProducts : '/products/getProducts/subCategories/',
  SearchProducts : '/products/getProducts/search/',
  Cart : '/user/details/cart',
  UpdateCart : '/user/details/updateCart',
  UserDetails : '/user/details/profileDetails',
  UpdateUserDetails : '/user/details/updateProfile',
  UploadProfileImage : '/user/details/profileUpload',
  Orders : '/user/orders/getOrders',
  PlaceOrder : '/user/orders/addOrders',
  Addresses : '/user/details/getAddresses',
  DeleteAddress : '/user/details/deleteAddress',
  UpdateAddress : '/user/details/updateAddress',
  Messages : '/user/details/getMessages/',
  SendMessage : '/user/details/sendMessage'
}

export const adminURLs = {
  CategoriesndSubCategories : "/admin/categoriesAndSubCategories",
  Products : "/admin/products",
  AddProduct : "/admin/products/addProduct",
  UpdateProductImage : '/admin/products/updateImage',
  TodaysInfo : '/admin/products/todayInfo',
  Customers : '/admin/customers',
  SingleCustomer : '/admin/customers/single-customer/',
  CustomerOrder : '/admin/customers/customer-order/',
  Messages : '/admin/getMessages/',
  SendMessage : '/admin/sendMessage',
  Orders : '/admin/orders/allOrders',
  TodayOrdersInfo : '/admin/orders/todayOrdersInfo',
  TodayProducts : '/admin/orders/todayProducts',
  OrderStatus : '/admin/orders/updateStatus/',
  CompareTwoProducts : '/admin/orders/weeklyCompare/',
  AdminDashboard : '/admin/adminDashboard',
  MonthlyDashboard : '/admin/adminDashboard/month/',
  CategoryDashboard : '/admin/adminDashboard/category/',
  SingleProduct : '/admin/adminDashboard/singleProductDetails/',
  SingleProductMonth : '/admin/adminDashboard/singleProduct/'
} 